default:
  image: eclipse-temurin:17

stages:
  - build

variables:
  COURSIER_CACHE: ".cache/coursier"

build_branch:
  stage: build
  script:
    - ./mill -i mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources || true
    - ./mill -i clean
    - ./mill -i _.compile
  artifacts:
    paths:
      - out/**/test/testReportDir.dest/TEST-*.xml
    reports:
      junit: out/**/test/testReportDir.dest/TEST-*.xml
